CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255) UNIQUE                               NOT NULL,
    email VARCHAR(512) UNIQUE                               NOT NULL
    );

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name        varchar(255) UNIQUE,
    description varchar(255),
    is_available   boolean,
    owner_id       integer REFERENCES users(id),
    request_id     integer
);






